package Vista.ConductoresCamionesAutorizados;

import Vista.Autorizacion.Autorizacion;
import Controlador.Autorizacion.ConsultarAutorizacion;
import Controlador.CamionesConductoresAutorizados.ConsultarAutorizados;
import Controlador.Conexion;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import Modelo.Autorizacion.Eliminar;
import java.sql.PreparedStatement;

//@author braya
public class ConductoresCamionesAutorizados extends javax.swing.JFrame {
    public ConductoresCamionesAutorizados() {
        initComponents();  // Inicializar los componentes de la interfaz
        setLocationRelativeTo(null);
        ConsultarAutorizacion consulta = new ConsultarAutorizacion();
        consulta.llenarComboBoxConductores(form_conductorautorizado_cc); 
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        form_conductorautorizado_cc = new javax.swing.JComboBox<>();
        form_conductorautorizado_conductor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Conductores y Camiones autorizados");

        jLabel2.setText("Seleccione uno de nuestros conductores para ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setText("ver qué vehiculos tiene autorizado conducir.");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Agrergar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Volver");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        form_conductorautorizado_cc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        form_conductorautorizado_cc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                form_conductorautorizado_ccMouseClicked(evt);
            }
        });
        form_conductorautorizado_cc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_conductorautorizado_ccActionPerformed(evt);
            }
        });

        form_conductorautorizado_conductor.setEditable(false);

        jLabel4.setText("Vehiculos Autorizados para manejar del conductor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(form_conductorautorizado_cc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(form_conductorautorizado_conductor, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(form_conductorautorizado_cc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(form_conductorautorizado_conductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String seleccion = (String) form_conductorautorizado_cc.getSelectedItem();
        ConsultarAutorizados consulta = new ConsultarAutorizados();
        consulta.mostrarPlacas(seleccion,jTable1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String seleccion = (String) form_conductorautorizado_cc.getSelectedItem();
        Autorizacion agregar = new Autorizacion(seleccion);
        agregar.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int filaSeleccionada = jTable1.getSelectedRow(); 
        String seleccion = (String) form_conductorautorizado_cc.getSelectedItem();

        if (filaSeleccionada != -1) { 
            Object valorCelda = jTable1.getValueAt(filaSeleccionada, 0); 
            int valorConvertido = Integer.parseInt(valorCelda.toString());

            int respuesta = JOptionPane.showConfirmDialog(null,"¿Está seguro de eliminar la autorizacion número " + valorConvertido + "?");
        
            if(respuesta == 0){
                Eliminar elimina = new Eliminar();
                elimina.Eliminar(valorConvertido);
                ConsultarAutorizados consulta = new ConsultarAutorizados();
                consulta.mostrarPlacas(seleccion,jTable1);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Debes seleccionar un vehículo para poder eliminarlo.");
        }
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void form_conductorautorizado_ccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_conductorautorizado_ccActionPerformed
        String seleccion = (String) form_conductorautorizado_cc.getSelectedItem();

        if (seleccion == null || seleccion.isEmpty()) {
            return; // Evita ejecutar si no hay selección
        }

        Conexion conexion = new Conexion();
        String sql = "SELECT Nombre || ' ' || Apellidos AS NombreCompleto FROM Conductor WHERE CC = ?";

        try {
            PreparedStatement pst = conexion.establecerConexion().prepareStatement(sql);
            pst.setInt(1, Integer.parseInt(seleccion)); // Convierte la selección a entero

            ResultSet rs = pst.executeQuery();

            if (rs.next()) { 
                String nombreCompleto = rs.getString("NombreCompleto");
                form_conductorautorizado_conductor.setText(nombreCompleto); // Rellena el JTextField
            } else {
                form_conductorautorizado_conductor.setText("No encontrado");
            }

            rs.close();
            pst.close();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_form_conductorautorizado_ccActionPerformed

    private void form_conductorautorizado_ccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_form_conductorautorizado_ccMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_form_conductorautorizado_ccMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> form_conductorautorizado_cc;
    private javax.swing.JTextField form_conductorautorizado_conductor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
