package Vista.Camion;

import Controlador.Camion.Consultar;
import Modelo.Camion.Insertar;
import Modelo.Camion.Actualizar;
import Modelo.Camion.Eliminar;
import Vista.Main;
import javax.swing.JOptionPane;

//@author Sergio Angel
public class Camion extends javax.swing.JFrame {

    /**
     * Creates new form Camion
     */
    public Camion() {
        initComponents();
        setLocationRelativeTo(null);
        Consultar consultar = new Consultar();
        consultar.mostrarCamiones(form_camiones_tabla);
    }
    
    public void Limpiar(){
        form_camiones_placa.setText("");
        form_camiones_marca.setText("");
        form_camiones_modelo.setText("");
        form_camiones_valor.setText("");
        form_camiones_aseguradora.setText("");
        form_camiones_km.setText("");
        form_camiones_chofer.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        form_camiones_placa = new javax.swing.JTextField();
        form_camiones_marca = new javax.swing.JTextField();
        form_camiones_modelo = new javax.swing.JTextField();
        form_camiones_valor = new javax.swing.JTextField();
        form_camiones_aseguradora = new javax.swing.JTextField();
        form_camiones_km = new javax.swing.JTextField();
        form_camiones_chofer = new javax.swing.JTextField();
        form_camiones_btn_registrar = new javax.swing.JButton();
        form_camiones_btn_actualizar = new javax.swing.JButton();
        form_camiones_btn_eliminar = new javax.swing.JButton();
        form_camiones_btn_salir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        form_camiones_tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(597, 600));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Camiones");

        jLabel2.setText("Placa");

        jLabel3.setText("Marca");

        jLabel4.setText("Modelo");

        jLabel5.setText("Valor");

        jLabel6.setText("Aseguradora");

        jLabel7.setText("Kilometraje");

        jLabel8.setText("Chofer");

        form_camiones_chofer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_camiones_choferActionPerformed(evt);
            }
        });

        form_camiones_btn_registrar.setText("Registrar");
        form_camiones_btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_camiones_btn_registrarActionPerformed(evt);
            }
        });

        form_camiones_btn_actualizar.setText("Actualizar");
        form_camiones_btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_camiones_btn_actualizarActionPerformed(evt);
            }
        });

        form_camiones_btn_eliminar.setText("Eliminar");
        form_camiones_btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_camiones_btn_eliminarActionPerformed(evt);
            }
        });

        form_camiones_btn_salir.setText("Volver");
        form_camiones_btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_camiones_btn_salirActionPerformed(evt);
            }
        });

        form_camiones_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        form_camiones_tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                form_camiones_tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(form_camiones_tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(form_camiones_placa, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(form_camiones_marca)
                    .addComponent(form_camiones_modelo)
                    .addComponent(form_camiones_valor)
                    .addComponent(form_camiones_aseguradora)
                    .addComponent(form_camiones_km)
                    .addComponent(form_camiones_chofer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(form_camiones_btn_registrar)
                    .addComponent(form_camiones_btn_actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(form_camiones_btn_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(form_camiones_btn_salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(form_camiones_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(form_camiones_btn_registrar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(form_camiones_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(form_camiones_btn_actualizar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(form_camiones_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(form_camiones_btn_eliminar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(form_camiones_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(form_camiones_btn_salir))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(form_camiones_aseguradora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(form_camiones_km, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(form_camiones_chofer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void form_camiones_btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_camiones_btn_registrarActionPerformed
        String Placa, Marca, Modelo, Valor, Aseguradora, km, Chofer;
        Placa = form_camiones_placa.getText().toString();
        Marca = form_camiones_marca.getText();
        Modelo = form_camiones_modelo.getText().toString();
        Valor = form_camiones_valor.getText().toString();
        Aseguradora = form_camiones_aseguradora.getText().toString();
        km = form_camiones_km.getText().toString();
        int kmint = Integer.parseInt(km);
        Chofer = form_camiones_chofer.getText().toString();
        
        if(!Placa.isEmpty() && !Marca.isEmpty() && !Modelo.isEmpty() && !Valor.isEmpty() && !Aseguradora.isEmpty() && !km.isEmpty() && !Chofer.isEmpty()){
            if(kmint>15000){
                JOptionPane.showMessageDialog(null, "Este camión supera los 15000 kilometros. No se puede agirnar.");
            }else{
                Insertar insertar = new Insertar();
                insertar.Adicionar(Placa, Marca, Modelo, Valor, Aseguradora, km, Chofer);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Todos los campos deben estar llenos.");
        }
        
        Consultar consultar = new Consultar();
        consultar.mostrarCamiones(form_camiones_tabla);
        Limpiar();
    }//GEN-LAST:event_form_camiones_btn_registrarActionPerformed

    private void form_camiones_btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_camiones_btn_actualizarActionPerformed
        String Placa, Marca, Modelo, Valor, Aseguradora, km, Chofer;
        Placa = form_camiones_placa.getText().toString();
        Marca = form_camiones_marca.getText().toString();
        Modelo = form_camiones_modelo.getText().toString();
        Valor = form_camiones_valor.getText().toString();
        Aseguradora = form_camiones_aseguradora.getText().toString();
        km = form_camiones_km.getText().toString();
        Chofer = form_camiones_chofer.getText().toString();
        
        Actualizar actualizar = new Actualizar();
        actualizar.Actualizar(Placa, Marca, Modelo, Valor, Aseguradora, km, Chofer);
        Consultar consultar = new Consultar();
        consultar.mostrarCamiones(form_camiones_tabla);
        Limpiar();
    }//GEN-LAST:event_form_camiones_btn_actualizarActionPerformed

    private void form_camiones_btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_camiones_btn_eliminarActionPerformed
        String Placa = form_camiones_placa.getText().toString();
        int res = JOptionPane.showConfirmDialog(null, "¿Está seguro?");
        if(res==0){
            Eliminar eliminar = new Eliminar();
            eliminar.Eliminar(Placa);
            Consultar consultar = new Consultar();
            consultar.mostrarCamiones(form_camiones_tabla);
            Limpiar();
        }
    }//GEN-LAST:event_form_camiones_btn_eliminarActionPerformed

    private void form_camiones_btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_camiones_btn_salirActionPerformed
        Main main = new Main();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_form_camiones_btn_salirActionPerformed

    private void form_camiones_choferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_camiones_choferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_form_camiones_choferActionPerformed

    private void form_camiones_tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_form_camiones_tablaMouseClicked
        int fila = form_camiones_tabla.getSelectedRow();
        form_camiones_placa.setText((String) form_camiones_tabla.getValueAt(fila, 0));
        form_camiones_marca.setText((String) form_camiones_tabla.getValueAt(fila, 1));
        form_camiones_modelo.setText((String) form_camiones_tabla.getValueAt(fila, 2));
        form_camiones_valor.setText((String) form_camiones_tabla.getValueAt(fila, 3));
        form_camiones_aseguradora.setText((String) form_camiones_tabla.getValueAt(fila, 4));
        form_camiones_km.setText((String) form_camiones_tabla.getValueAt(fila, 5));
        form_camiones_chofer.setText((String) form_camiones_tabla.getValueAt(fila, 6));
    }//GEN-LAST:event_form_camiones_tablaMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField form_camiones_aseguradora;
    private javax.swing.JButton form_camiones_btn_actualizar;
    private javax.swing.JButton form_camiones_btn_eliminar;
    private javax.swing.JButton form_camiones_btn_registrar;
    private javax.swing.JButton form_camiones_btn_salir;
    private javax.swing.JTextField form_camiones_chofer;
    private javax.swing.JTextField form_camiones_km;
    private javax.swing.JTextField form_camiones_marca;
    private javax.swing.JTextField form_camiones_modelo;
    private javax.swing.JTextField form_camiones_placa;
    private javax.swing.JTable form_camiones_tabla;
    private javax.swing.JTextField form_camiones_valor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
