/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.accidente.consultaraccidentes;
import Modelo.Accidente.Actualizar;
import Modelo.Accidente.Eliminar;
import Modelo.Accidente.Insertar;
import javax.swing.JOptionPane;

/**
 *
 * @author brayan
 */
public class GestionAccidentes extends javax.swing.JFrame {

    /**
     * Creates new form GestionAcccidentes
     */
    public GestionAccidentes() {
        initComponents();
        consultaraccidentes consulta = new consultaraccidentes();
        consulta.mostrarAccidentes(jTable1);
        
    }
    
        public void Limpiar(){
           from_accidentes_ID.setText("");
        form_accidente_fecha.setText("");
        form_accidente_conductor.setText("");
        form_accidente_vehiculo.setText("");
        form_accidente_costo.setText("");
        form_accidente_descri.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        from_accidentes_ID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        form_accidente_fecha = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        form_accidente_descri = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        form_accidente_vehiculo = new javax.swing.JTextField();
        form_accidente_conductor = new javax.swing.JTextField();
        form_accidente_costo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        BtnActualizar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Accidentes");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        from_accidentes_ID.setEditable(false);
        from_accidentes_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                from_accidentes_IDActionPerformed(evt);
            }
        });

        jLabel2.setText("ID");

        jLabel3.setText("Fecha");

        form_accidente_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_accidente_fechaActionPerformed(evt);
            }
        });

        form_accidente_descri.setColumns(20);
        form_accidente_descri.setRows(5);
        jScrollPane2.setViewportView(form_accidente_descri);

        jLabel4.setText("Descripccion");

        jLabel5.setText("Costo de daños");

        jLabel6.setText("Conductor");

        jLabel7.setText("Vehiculo");

        form_accidente_vehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_accidente_vehiculoActionPerformed(evt);
            }
        });

        form_accidente_conductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_accidente_conductorActionPerformed(evt);
            }
        });

        form_accidente_costo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_accidente_costoActionPerformed(evt);
            }
        });

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BtnActualizar.setText("Actualizar");
        BtnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActualizarActionPerformed(evt);
            }
        });

        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(form_accidente_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(from_accidentes_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(form_accidente_conductor, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(form_accidente_vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(form_accidente_costo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(from_accidentes_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(form_accidente_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(form_accidente_conductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(form_accidente_vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(form_accidente_costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

         // Definir variable para el manejo de la fila de la tabla donde se pulsa el click
        int fila = jTable1.getSelectedRow();
        
        from_accidentes_ID.setText((String) jTable1.getValueAt(fila,0) );
        form_accidente_fecha.setText((String) jTable1.getValueAt(fila,1) );
        form_accidente_conductor.setText((String) jTable1.getValueAt(fila,2) );
        form_accidente_vehiculo.setText((String) jTable1.getValueAt(fila,3) );
        form_accidente_costo.setText((String) jTable1.getValueAt(fila,4) );
        form_accidente_descri.setText((String) jTable1.getValueAt(fila,5) );
    }//GEN-LAST:event_jTable1MouseClicked

    private void from_accidentes_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_from_accidentes_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_from_accidentes_IDActionPerformed

    private void form_accidente_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_accidente_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_form_accidente_fechaActionPerformed

    private void form_accidente_vehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_accidente_vehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_form_accidente_vehiculoActionPerformed

    private void form_accidente_conductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_accidente_conductorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_form_accidente_conductorActionPerformed

    private void form_accidente_costoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_accidente_costoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_form_accidente_costoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String conductor,fecha,placa, Descripccion, costo;
        fecha = form_accidente_fecha.getText().toString();
        conductor = form_accidente_conductor.getText();
        placa = form_accidente_vehiculo.getText().toString();
        costo = form_accidente_costo.getText().toString();
        Descripccion = form_accidente_descri.getText().toString();
        
        int conductorCc= Integer.parseInt(conductor); // Convertir a int
        float costofloat = Float.parseFloat(costo); // Convertir a float
        
        if(!fecha.isEmpty() && !conductor.isEmpty() && !costo.isEmpty() && !Descripccion.isEmpty() && !placa.isEmpty()){
            Insertar insertar = new Insertar();
            insertar.Adicionar(fecha, conductorCc, placa, costofloat, Descripccion);
            consultaraccidentes consulta = new consultaraccidentes();
            consulta.mostrarAccidentes(jTable1);
            Limpiar();
        }else{
            JOptionPane.showMessageDialog(null, "Todos los campos deben estar llenos.");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarActionPerformed
        // TODO add your handling code here:
        String idf, conductor,fecha,placa, Descripccion, costo;
        idf = from_accidentes_ID.getText().toString();
        fecha = form_accidente_fecha.getText().toString();
        conductor = form_accidente_conductor.getText();
        placa = form_accidente_vehiculo.getText().toString();
        costo = form_accidente_costo.getText().toString();
        Descripccion = form_accidente_descri.getText().toString();
        
        int conductorCc= Integer.parseInt(conductor); // Convertir a int
        float costofloat = Float.parseFloat(costo); // Convertir a float
        int Idint = Integer.parseInt(idf);
        
        Actualizar actualizar = new Actualizar();
        actualizar.Actualizar(Idint, fecha ,conductorCc ,placa , costofloat , Descripccion);
        consultaraccidentes consulta = new consultaraccidentes();
        consulta.mostrarAccidentes(jTable1);
        Limpiar();
        
    }//GEN-LAST:event_BtnActualizarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
                String idf = from_accidentes_ID.getText().toString();
        
        int IntID = Integer.parseInt(idf);
        int respuesta = JOptionPane.showConfirmDialog(null,"Esta segudo de eliminar accidente" + idf);
        if(respuesta == 0){
        Eliminar eliminar = new Eliminar();
        eliminar.Eliminar(IntID);
        consultaraccidentes consulta = new consultaraccidentes();
        consulta.mostrarAccidentes(jTable1);
        Limpiar();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        // TODO add your handling code here:
        Main menu = new Main();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionAccidentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionAccidentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionAccidentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionAccidentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionAccidentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JButton Volver;
    private javax.swing.JTextField form_accidente_conductor;
    private javax.swing.JTextField form_accidente_costo;
    private javax.swing.JTextArea form_accidente_descri;
    private javax.swing.JTextField form_accidente_fecha;
    private javax.swing.JTextField form_accidente_vehiculo;
    private javax.swing.JTextField from_accidentes_ID;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
