package Vista.Autorizacion;

import Controlador.Conexion;
import Controlador.CamionesConductoresAutorizados.ConsultarAutorizados;
import Modelo.Autorizacion.Insertar;
import Vista.ConductoresCamionesAutorizados.ConductoresCamionesAutorizados;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

//@author braya
public class Autorizacion extends javax.swing.JFrame {
    private String ccConductor; // Guardamos el CC del conductor
     
    public Autorizacion(){
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public Autorizacion(String ccConductor) {
        initComponents();
        this.ccConductor = ccConductor;
        llenarPlacasDisponibles();
    }
    
    private void llenarPlacasDisponibles() {
        Conexion conexion = new Conexion();
        String sql = "SELECT Placa FROM Camion WHERE Placa NOT IN (SELECT Placa_Vehiculo FROM Camiones_autorizados WHERE CC_conductor = ?)";
        try{
            PreparedStatement pst = conexion.establecerConexion().prepareStatement(sql);
            pst.setString(1, ccConductor);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                form_placa_agregarautorizadas.addItem(rs.getString("Placa"));
            }
        }
        catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        form_placa_agregarautorizadas = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seleccione el vehiculo que desea agregar");

        form_placa_agregarautorizadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_placa_agregarautorizadasActionPerformed(evt);
            }
        });

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jButton1)
                .addGap(48, 48, 48)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 42, Short.MAX_VALUE)
                .addComponent(form_placa_agregarautorizadas, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(form_placa_agregarautorizadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void form_placa_agregarautorizadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_placa_agregarautorizadasActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_form_placa_agregarautorizadasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String placa = (String) form_placa_agregarautorizadas.getSelectedItem();
        Insertar insertar = new Insertar();
        insertar.Adicionar(Integer.parseInt(ccConductor), placa);
        this.dispose();
        ConsultarAutorizados consulta = new ConsultarAutorizados();
        String seleccion = (String) ConductoresCamionesAutorizados.form_conductorautorizado_cc.getSelectedItem();
        consulta.mostrarPlacas(seleccion, ConductoresCamionesAutorizados.jTable1);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> form_placa_agregarautorizadas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
