package Vista.Viaje;

//@author chech

import Controlador.Viaje.Consultar;
import Modelo.Viaje.Actualizar;
import Modelo.Viaje.Eliminar;
import Modelo.Viaje.Insertar;
import javax.swing.JOptionPane;


public class Viaje extends javax.swing.JFrame {
    public Viaje() {
        initComponents();
        setLocationRelativeTo(null);
        Consultar consultar = new Consultar();
        consultar.mostrarViajes(form_viajes_tabla);
    }
    
    public void Limpiar(){
        form_viajes_ID.setText("");
        form_viajes_CC.setText("");
        form_viajes_placa.setText("");
        form_viajes_destino.setText("");
        form_viajes_origen.setText("");
        form_viajes_fecha_salida.setText("");
        form_viajes_fecha_llegada.setText("");
        form_viajes_ID_bulto.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        form_viajes_ID = new javax.swing.JTextField();
        form_viajes_CC = new javax.swing.JTextField();
        form_viajes_placa = new javax.swing.JTextField();
        form_viajes_destino = new javax.swing.JTextField();
        form_viajes_origen = new javax.swing.JTextField();
        form_viajes_fecha_salida = new javax.swing.JTextField();
        form_viajes_fecha_llegada = new javax.swing.JTextField();
        form_viajes_ID_bulto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        form_viajes_tabla = new javax.swing.JTable();
        form_viajes_btn_registrar = new javax.swing.JButton();
        form_viajes_btn_actualizar = new javax.swing.JButton();
        form_viajes_btn_eliminar = new javax.swing.JButton();
        form_viajes_btn_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Viajes");

        jLabel2.setText("ID");

        jLabel3.setText("CC");

        jLabel4.setText("Placa");

        jLabel5.setText("Destino");

        jLabel6.setText("Origen");

        jLabel7.setText("Fecha De Salida");

        jLabel8.setText("Fecha de Llegada");

        jLabel9.setText("ID Bulto");

        form_viajes_ID.setEditable(false);
        form_viajes_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_viajes_IDActionPerformed(evt);
            }
        });

        form_viajes_placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_viajes_placaActionPerformed(evt);
            }
        });

        form_viajes_origen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_viajes_origenActionPerformed(evt);
            }
        });

        form_viajes_fecha_llegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_viajes_fecha_llegadaActionPerformed(evt);
            }
        });

        form_viajes_ID_bulto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_viajes_ID_bultoActionPerformed(evt);
            }
        });

        form_viajes_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        form_viajes_tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                form_viajes_tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(form_viajes_tabla);

        form_viajes_btn_registrar.setText("Registrar");
        form_viajes_btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_viajes_btn_registrarActionPerformed(evt);
            }
        });

        form_viajes_btn_actualizar.setText("Actualizar");
        form_viajes_btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_viajes_btn_actualizarActionPerformed(evt);
            }
        });

        form_viajes_btn_eliminar.setText("Eliminar");
        form_viajes_btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_viajes_btn_eliminarActionPerformed(evt);
            }
        });

        form_viajes_btn_salir.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(form_viajes_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(form_viajes_CC, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(form_viajes_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(form_viajes_destino, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(form_viajes_origen, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(form_viajes_fecha_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(form_viajes_fecha_llegada, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(form_viajes_ID_bulto, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(form_viajes_btn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(form_viajes_btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(form_viajes_btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(form_viajes_btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(form_viajes_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(form_viajes_btn_registrar))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(form_viajes_CC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(form_viajes_btn_actualizar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(form_viajes_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(form_viajes_btn_eliminar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(form_viajes_destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(form_viajes_btn_salir))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(form_viajes_origen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(form_viajes_fecha_salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addComponent(form_viajes_fecha_llegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(form_viajes_ID_bulto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void form_viajes_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_viajes_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_form_viajes_IDActionPerformed

    private void form_viajes_placaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_viajes_placaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_form_viajes_placaActionPerformed

    private void form_viajes_btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_viajes_btn_registrarActionPerformed
        String CC, Placa, Destino, Origen, FechaSalida, FechaLlegada, ID_Bulto;
        CC = form_viajes_CC.getText().toString();
        Placa = form_viajes_placa.getText();
        Destino = form_viajes_destino.getText().toString();
        Origen = form_viajes_origen.getText().toString();
        FechaSalida = form_viajes_fecha_salida.getText().toString();
        FechaLlegada = form_viajes_fecha_llegada.getText().toString();
        ID_Bulto = form_viajes_ID_bulto.getText().toString();
        
        if(!CC.isEmpty() && !Placa.isEmpty() && !Destino.isEmpty() && !Origen.isEmpty() && !FechaSalida.isEmpty() && !FechaLlegada.isEmpty() && !ID_Bulto.isEmpty()){
            Insertar insertar = new Insertar();
            insertar.Adicionar(CC, Placa, Destino, FechaSalida, FechaSalida, FechaLlegada, ID_Bulto);
        }else{
            JOptionPane.showMessageDialog(null, "Todos los campos deben estar llenos.");
        }
        
        Consultar consultar = new Consultar();
        consultar.mostrarViajes(form_viajes_tabla);
        Limpiar();
    }//GEN-LAST:event_form_viajes_btn_registrarActionPerformed

    private void form_viajes_btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_viajes_btn_actualizarActionPerformed
        String ID_viaje, CC, Placa, Destino, Origen, Fecha_salida, Fecha_llegada, ID_Bulto;
        ID_viaje = form_viajes_ID.getText().toString();
        CC = form_viajes_CC.getText().toString();
        Placa = form_viajes_placa.getText().toString();
        Destino = form_viajes_destino.getText().toString();
        Origen = form_viajes_origen.getText().toString();
        Fecha_salida = form_viajes_fecha_salida.getText().toString();
        Fecha_llegada = form_viajes_fecha_llegada.getText().toString();
        ID_Bulto = form_viajes_ID_bulto.getText().toString();
        int IDint = Integer.parseInt(ID_viaje);
        
        Actualizar actualizar = new Actualizar();
        actualizar.Actualizar(IDint, CC, Placa, Destino, Origen, Fecha_salida, Fecha_llegada, ID_Bulto);
        Consultar consultar = new Consultar();
        consultar.mostrarViajes(form_viajes_tabla);
        Limpiar();
    }//GEN-LAST:event_form_viajes_btn_actualizarActionPerformed

    private void form_viajes_tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_form_viajes_tablaMouseClicked
        int fila = form_viajes_tabla.getSelectedRow();
        form_viajes_ID.setText((String) form_viajes_tabla.getValueAt(fila, 0));
        form_viajes_CC.setText((String) form_viajes_tabla.getValueAt(fila, 1));
        form_viajes_placa.setText((String) form_viajes_tabla.getValueAt(fila, 2));
        form_viajes_destino.setText((String) form_viajes_tabla.getValueAt(fila, 3));
        form_viajes_origen.setText((String) form_viajes_tabla.getValueAt(fila, 4));
        form_viajes_fecha_salida.setText((String) form_viajes_tabla.getValueAt(fila, 5));
        form_viajes_fecha_llegada.setText((String) form_viajes_tabla.getValueAt(fila, 6));
        form_viajes_ID_bulto.setText((String) form_viajes_tabla.getValueAt(fila, 7));
    }//GEN-LAST:event_form_viajes_tablaMouseClicked

    private void form_viajes_ID_bultoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_viajes_ID_bultoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_form_viajes_ID_bultoActionPerformed

    private void form_viajes_origenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_viajes_origenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_form_viajes_origenActionPerformed

    private void form_viajes_fecha_llegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_viajes_fecha_llegadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_form_viajes_fecha_llegadaActionPerformed

    private void form_viajes_btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_viajes_btn_eliminarActionPerformed
        String ID = form_viajes_ID.getText().toString();
        int IDint = Integer.parseInt(ID);
        int res = JOptionPane.showConfirmDialog(null, "¿Está seguro?");
        if(res==0){
            Eliminar eliminar = new Eliminar();
            eliminar.Eliminar(IDint);
            Consultar consultar = new Consultar();
            consultar.mostrarViajes(form_viajes_tabla);
            Limpiar();
        }
    }//GEN-LAST:event_form_viajes_btn_eliminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField form_viajes_CC;
    private javax.swing.JTextField form_viajes_ID;
    private javax.swing.JTextField form_viajes_ID_bulto;
    private javax.swing.JButton form_viajes_btn_actualizar;
    private javax.swing.JButton form_viajes_btn_eliminar;
    private javax.swing.JButton form_viajes_btn_registrar;
    private javax.swing.JButton form_viajes_btn_salir;
    private javax.swing.JTextField form_viajes_destino;
    private javax.swing.JTextField form_viajes_fecha_llegada;
    private javax.swing.JTextField form_viajes_fecha_salida;
    private javax.swing.JTextField form_viajes_origen;
    private javax.swing.JTextField form_viajes_placa;
    private javax.swing.JTable form_viajes_tabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
